### ISSUE TITLE
It really does not create fat file even when requirements file is created

### ISSUE THREAD

**Issue by anupash147** [alekseyig/PyAssembly#1]
I have created 2 projects with full requirement files but it does not create any fat egg like told. Can you tell me if there is any specific thing i have to be looking for

**Comment by alekseyig** [comment]
Anup,

Can you send me your requirement file and the command you used to build the egg file?

Aleksey

On Sat, May 11, 2019 at 12:37 PM Anup Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

I have created 2 projects with full requirement files but it does not create any fat egg like told. Can you tell me if there is any specific thing i have to be looking for

**Comment by alekseyig** [comment]
@anupash147 

Can you send me your requirement file and the command you used to build the egg file?

Aleksey

**Comment by anupash147** [comment]
Here is a very basic project just having requirement file 

With Regards,
Anup Ash 

    On Saturday, 11 May 2019, 7:34:02 pm EDT, Aleksey Zhukov <notifications@github.com> wrote:  
 
 Anup,

Can you send me your requirement file and the command you used to build the egg file?

Aleksey

On Sat, May 11, 2019 at 12:37 PM Anup Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

I have created 2 projects with full requirement files but it does not create any fat egg like told. Can you tell me if there is any specific thing i have to be looking for

**Comment by alekseyig** [comment]
@anupash147 , sorry, but i do not see your requirement file.
also, please send the command you executed to build the fat egg.

**Comment by anupash147** [comment]
Sorry. I attached wrong package. Apologize for the inconvenience.


With Regards,
Anup Ash 

    On Sunday, 12 May 2019, 7:47:13 pm EDT, ash anup <anupash147@yahoo.com> wrote:  
 
 
Here is a very basic project just having requirement file 

With Regards,
Anup Ash 

    On Saturday, 11 May 2019, 7:34:02 pm EDT, Aleksey Zhukov <notifications@github.com> wrote:  
 
 Anup,

Can you send me your requirement file and the command you used to build the egg file?

Aleksey

On Sat, May 11, 2019 at 12:37 PM Anup Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

I have created 2 projects with full requirement files but it does not create any fat egg like told. Can you tell me if there is any specific thing i have to be looking for

**Comment by alekseyig** [comment]
@anupash147 
Github does not really handle the attachments, you need to include it in the body.
Please provide:
- the name and the content of your requirement file
- the command(s) you used to build the fat egg.

**Comment by alekseyig** [comment]
@anupash147, i am closing this one.
