### ISSUE TITLE
Permission denied error in windows while accessing requirements.txt file

### ISSUE THREAD

**Issue by jsanjay63** [alekseyig/PyAssembly#4]
I tried creating an "uber" egg file for my module. In windows, it gives error as permission denied:
`ERROR: Could not open requirements file: [Errno 13] Permission denied: 'C:\\Users\\sajain\\AppData\\Local\\Temp\\tmpc1o1uzq3'`

I tried executing with administrative privilege as well..but same error.

**Comment by alekseyig** [comment]
@jsanjay63, unfortunately i do not have access to windows machine and cannot check it right now, but it seems strange to me that it tries to access requirements file from some temp location. 
Can you check if it is correct and expected path? 
Can you check that your user has access to intermediate folders in this path?
May be you can provide more info how you call pyassembly?

**Comment by jsanjay63** [comment]
In main.py, requirements.txt file is copied to a temporary directory. I solved this issue by updating:
`with tempfile.NamedTemporaryFile(mode='w+')` to `with tempfile.NamedTemporaryFile(mode='w+', delete=False)`

I searched for solution online and it was suggested to use: delete=False in Windows.
